title = "samienr"
base_url = "https://samienr.com"
description = "Nerd"
theme = "duckquill"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
author = "Samien Rahman"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "rose-pine-dark", filename = "syntax-theme-dark.css" },
  { theme = "rose-pine-light", filename = "syntax-theme-light.css" },
]
smart_punctuation = true

[search]
index_format = "elasticlunr_json"

[extra]
primary_color = "rgb(101, 143, 239)"
primary_color_alpha = "rgba(101, 143, 239, .2)"
primary_color_dark = "rgb(140, 170, 238)"
primary_color_dark_alpha = "rgba(140, 170, 238, .2)"
emoji_favicon = false
animated_favicon = false
issues_url = "https://github.com/samienr/zola-website/issues"
source_url = "https://github.com/samienr/zola-website"

# Additional CSS stylesheets; expects them to be in the "./static/" directory.
# If you are using Sass it will be generated there automatically.
stylesheets = [
   "footer.css",
   "typography.css",
]
### TODO:: ADD THE JS SCRIPTS FROM THE HTML HEAD FROM THE OG
# Additional JavaScript scripts; expects them to be in the "./static/" directory.
#scripts = [
#  "katex.min.js",
#]
show_copy_button = true
show_read_time = true

[extra.nav]
# Whether to show Atom/RSS feed button in the nav
show_feed = true
# Links used in the nav.
# For local files use same link format as in Markdown,
# i.e "@/blog/_index.md".
# See https://www.getzola.org/documentation/content/linking/#internal-links
links = [
  { url = "@/about/index.md", name = "About" },
  { url = "@/blog/_index.md", name = "Blog" },
  { url = "@/contact.md", name = "Contact" },
]

[extra.footer]
links = [
      { url = "@/notebook/_index.md", name = "Notebook" },
      { url = "@/photography/index.md", name = "Photography" },
]

show_copyright = true
show_powered_by = false
#show_source = true

[extra.goatcounter]
user = "samienr"
