title = "samienr"
base_url = "https://samienr.com"
description = "Electrical Nerd + Digital Artist"
theme = "duckquill"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
author = "Samien Rahman"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "nord"
#highlight_theme = "css"
#highlight_themes_css = [
#  { theme = "rose-pine-dark", filename = "syntax-theme-dark.css" },
#  { theme = "rose-pine-light", filename = "syntax-theme-light.css" },
#]
smart_punctuation = false

[search]
index_format = "elasticlunr_json"

[extra]
accent_color = "rgb(101, 143, 239)"
accent_color_dark = "rgb(140, 170, 238)"
emoji_favicon = false
animated_favicon = false
issues_url = "https://github.com/samienr/zola-website/issues"
source_url = "https://github.com/samienr/zola-website"

# Additional CSS stylesheets; expects them to be in the "./static/" directory.
# If you are using Sass it will be generated there automatically.
styles = [
   "footer.css",
   "typography.css",
   "notebook.css",
]
show_copy_button = true
show_reading_time = true
show_backlinks = true

#katex = true

[extra.nav]
# Whether to show Atom/RSS feed button in the nav
show_feed = true
show_theme_switcher = true
# Links used in the nav.
# For local files use same link format as in Markdown,
# i.e "@/blog/_index.md".
# See https://www.getzola.org/documentation/content/linking/#internal-links
links = [
  { url = "@/photography/index.md", name = "Gallery" },
  { url = "@/blog/_index.md", name = "Blog" },
  { url = "@/contact.md", name = "Contact" },
]

[extra.footer]
links = [
  { url = "/tags/projects", name = "Projects" },
  { url = "@/notebook/_index.md", name = "Notebook" },
  { url = "@/resume/index.md", name = "Resume" },
]

show_copyright = true
#show_powered_by = true
